SET LOCAL search_path = store_portal, public;

CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL CHECK (role IN ('store_owner', 'customer')),
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL CHECK (length(trim(full_name)) BETWEEN 2 AND 100),
  email_verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_users_email_nocase ON users(lower(email));

CREATE TABLE businesses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 2 AND 120),
  description TEXT NOT NULL DEFAULT '' CHECK (length(description) <= 1000),
  contact_email TEXT NOT NULL CHECK (length(trim(contact_email)) <= 254),
  phone TEXT NOT NULL DEFAULT '' CHECK (length(phone) <= 24),
  address_line TEXT NOT NULL DEFAULT '' CHECK (length(address_line) <= 250),
  wilayat TEXT NOT NULL DEFAULT '' CHECK (length(wilayat) <= 100),
  governorate TEXT NOT NULL DEFAULT '' CHECK (length(governorate) <= 100),
  application_status TEXT NOT NULL DEFAULT 'draft'
    CHECK (application_status IN ('draft', 'pending', 'approved', 'rejected', 'suspended')),
  status_reason TEXT NOT NULL DEFAULT '' CHECK (length(status_reason) <= 500),
  is_temporarily_closed INTEGER NOT NULL DEFAULT 0 CHECK (is_temporarily_closed IN (0, 1)),
  closure_note TEXT NOT NULL DEFAULT '' CHECK (length(closure_note) <= 250),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE business_documents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
  document_type TEXT NOT NULL CHECK (length(trim(document_type)) BETWEEN 2 AND 50),
  storage_key TEXT NOT NULL UNIQUE,
  original_name TEXT NOT NULL CHECK (length(original_name) <= 255),
  mime_type TEXT NOT NULL CHECK (length(mime_type) <= 100),
  size_bytes INTEGER NOT NULL CHECK (size_bytes > 0),
  review_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (review_status IN ('pending', 'accepted', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE business_hours (
  business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  is_closed INTEGER NOT NULL DEFAULT 1 CHECK (is_closed IN (0, 1)),
  opens_at TEXT,
  closes_at TEXT,
  PRIMARY KEY (business_id, day_of_week),
  CHECK (
    (is_closed = 1 AND opens_at IS NULL AND closes_at IS NULL)
    OR
    (is_closed = 0 AND opens_at IS NOT NULL AND closes_at IS NOT NULL AND opens_at < closes_at)
  )
);

CREATE TABLE service_areas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 2 AND 100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (business_id, name)
);

CREATE TABLE categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 2 AND 80),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_categories_business_name_nocase
  ON categories(business_id, lower(name));

CREATE TABLE dishes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
  category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 2 AND 120),
  description TEXT NOT NULL DEFAULT '' CHECK (length(description) <= 1000),
  price_baisa INTEGER NOT NULL CHECK (price_baisa >= 0),
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'active', 'unavailable', 'archived')),
  archived_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dish_images (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dish_id INTEGER NOT NULL REFERENCES dishes(id) ON DELETE CASCADE,
  storage_key TEXT NOT NULL UNIQUE,
  alt_text TEXT NOT NULL DEFAULT '' CHECK (length(alt_text) <= 250),
  display_order INTEGER NOT NULL DEFAULT 0 CHECK (display_order >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
  customer_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  order_number TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (
      status IN (
        'pending',
        'accepted',
        'preparing',
        'ready',
        'completed',
        'rejected',
        'cancelled'
      )
    ),
  subtotal_baisa INTEGER NOT NULL CHECK (subtotal_baisa >= 0),
  delivery_fee_baisa INTEGER NOT NULL DEFAULT 0 CHECK (delivery_fee_baisa >= 0),
  total_baisa INTEGER NOT NULL CHECK (total_baisa >= 0),
  customer_name TEXT NOT NULL CHECK (length(trim(customer_name)) BETWEEN 2 AND 100),
  customer_phone TEXT NOT NULL CHECK (length(trim(customer_phone)) BETWEEN 5 AND 24),
  delivery_address TEXT NOT NULL CHECK (length(trim(delivery_address)) BETWEEN 5 AND 500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
  dish_id INTEGER REFERENCES dishes(id) ON DELETE SET NULL,
  dish_name TEXT NOT NULL CHECK (length(trim(dish_name)) BETWEEN 2 AND 120),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price_baisa INTEGER NOT NULL CHECK (unit_price_baisa >= 0),
  line_total_baisa INTEGER NOT NULL CHECK (line_total_baisa >= 0)
);

CREATE TABLE order_status_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
  changed_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  from_status TEXT,
  to_status TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '' CHECK (length(reason) <= 500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  csrf_token TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE RESTRICT,
  actor_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  action TEXT NOT NULL CHECK (length(trim(action)) BETWEEN 2 AND 100),
  resource_type TEXT NOT NULL CHECK (length(trim(resource_type)) BETWEEN 2 AND 50),
  resource_id INTEGER,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_business_documents_business ON business_documents(business_id);
CREATE INDEX idx_service_areas_business ON service_areas(business_id);
CREATE INDEX idx_categories_business ON categories(business_id);
CREATE INDEX idx_dishes_business_status ON dishes(business_id, status);
CREATE INDEX idx_orders_business_created ON orders(business_id, created_at DESC);
CREATE INDEX idx_orders_business_status ON orders(business_id, status);
CREATE INDEX idx_orders_business_number ON orders(business_id, order_number);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_history_order ON order_status_history(order_id, created_at);
CREATE INDEX idx_sessions_expiry ON sessions(expires_at);
CREATE INDEX idx_audit_business_created ON audit_events(business_id, created_at DESC);

INSERT INTO categories (business_id, name)
SELECT businesses.id, defaults.name
FROM businesses
CROSS JOIN (
  VALUES
    ('Main dishes'),
    ('Appetizers'),
    ('Sweets & Desserts'),
    ('Breads'),
    ('Drinks')
) AS defaults(name)
ON CONFLICT DO NOTHING;
